services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: coesione-client
    depends_on:
      server:
        condition: service_started
    networks:
      - default
      - proxynet
    labels:
      - "traefik.docker.network=proxynet"
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.front.entrypoints=https"
      - "traefik.http.routers.front.tls=true"
      # - "traefik.http.routers.front.tls.certresolver=cloudflare"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
      - "traefik.http.routers.front-http.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.front-http.entrypoints=http"
      - "traefik.http.routers.front-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3000"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  server:
    build: ./server
    container_name: coesione-server
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=3001
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1:3001/api/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  proxynet:
    external: true
