services:
  coesione-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: coesione-client
    depends_on:
      - coesione-server
    networks:
      - default
      - proxynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.coesione.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.coesione.entrypoints=https"
      - "traefik.http.routers.coesione.tls=true"
      # - "traefik.http.routers.coesione.tls.certresolver=cloudflare"
      - "traefik.http.services.coesione.loadbalancer.server.port=3000"
      - "traefik.http.routers.coesione-http.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.coesione-http.entrypoints=http"
      - "traefik.http.routers.coesione-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: unless-stopped

  coesione-server:
    build: ./server
    container_name: coesione-server
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=3001
    networks:
      - proxynet
      - default
    restart: unless-stopped

networks:
  default: {}
  proxynet:
    external: true
