services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: coesione-client
    depends_on:
      - server
    networks:
      - default
      - proxynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.front.entrypoints=https"
      - "traefik.http.routers.front.tls=true"
      # - "traefik.http.routers.front.tls.certresolver=cloudflare"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
      - "traefik.http.routers.front-http.rule=Host(`dev-coesione.robinweb.it`)"
      - "traefik.http.routers.front-http.entrypoints=http"
      - "traefik.http.routers.front-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: unless-stopped

  server:
    build: ./server
    container_name: coesione-server
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=3001
    networks:
      - default
    restart: unless-stopped

networks:
  proxynet:
    external: true
